In [31]:
import numpy as np
np.random.seed(0)
X = np.random.rand(10000000)

In [32]:
%time X.sort()

CPU times: user 766 ms, sys: 0 ns, total: 766 ms
Wall time: 766 ms


In [33]:
print(X)

[2.52e-08 1.64e-07 1.89e-07 ... 1.00e+00 1.00e+00 1.00e+00]


In [34]:
%timeit np.searchsorted(X,0.5)

936 ns ± 2.25 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [35]:
Y = np.random.random((4,5))

In [36]:
np.set_printoptions(precision = 2)

In [37]:
print(Y)

[[0.96 0.92 1.   0.71 0.22]
 [0.63 0.34 0.82 0.97 0.33]
 [0.98 0.44 0.95 0.33 0.73]
 [0.04 0.16 0.96 0.87 0.88]]


In [38]:
i_sort = np.argsort(Y[:,0])

In [39]:
print(Y[i_sort])  
#sorts the first column and swaps the positions of the numbers for each column after that corresponding to the first sort

[[0.04 0.16 0.96 0.87 0.88]
 [0.63 0.34 0.82 0.97 0.33]
 [0.96 0.92 1.   0.71 0.22]
 [0.98 0.44 0.95 0.33 0.73]]


In [40]:
Y.sort(0)
print(Y)
#Every column has now been sorted but the values in each row are no longer associated
    #this can lead to meaningless data and must be taken into account
        #if Y represents an array of observations for example

[[0.04 0.16 0.82 0.33 0.22]
 [0.63 0.34 0.95 0.71 0.33]
 [0.96 0.44 0.96 0.87 0.73]
 [0.98 0.92 1.   0.97 0.88]]
